//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace exam_8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transition
    {
        public int FirstStationId { get; set; }
        public int SecondStationId { get; set; }
        public Nullable<int> MinutesToTransit { get; set; }
    
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
    }
}
